# Generated by Django 4.2.5 on 2023-10-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="stubgrp",
            field=models.CharField(default="Not available", max_length=10),
        ),
    ]
